// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNduClpiB0a1rsm5zUE7wiG1swCPr71A',
    appId: '1:209354446525:web:2405d0629a9639d292c9d4',
    messagingSenderId: '209354446525',
    projectId: 'repharma-1d470',
    authDomain: 'repharma-1d470.firebaseapp.com',
    storageBucket: 'repharma-1d470.firebasestorage.app',
    measurementId: 'G-H847YEYB0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_yJVaRxLWxnL8Hhy2SAWQL-su18zc-I',
    appId: '1:209354446525:android:0ba0901f8e2a638192c9d4',
    messagingSenderId: '209354446525',
    projectId: 'repharma-1d470',
    storageBucket: 'repharma-1d470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVpQvOzwmQZXssPsNj3WOoWabRck0sVc',
    appId: '1:209354446525:ios:04d80c3d4f07f9c192c9d4',
    messagingSenderId: '209354446525',
    projectId: 'repharma-1d470',
    storageBucket: 'repharma-1d470.firebasestorage.app',
    iosBundleId: 'com.example.repharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVpQvOzwmQZXssPsNj3WOoWabRck0sVc',
    appId: '1:209354446525:ios:04d80c3d4f07f9c192c9d4',
    messagingSenderId: '209354446525',
    projectId: 'repharma-1d470',
    storageBucket: 'repharma-1d470.firebasestorage.app',
    iosBundleId: 'com.example.repharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNduClpiB0a1rsm5zUE7wiG1swCPr71A',
    appId: '1:209354446525:web:e6203ba1c4fa767192c9d4',
    messagingSenderId: '209354446525',
    projectId: 'repharma-1d470',
    authDomain: 'repharma-1d470.firebaseapp.com',
    storageBucket: 'repharma-1d470.firebasestorage.app',
    measurementId: 'G-6HB8FKHYX9',
  );
}
