import 'package:cloud_firestore/cloud_firestore.dart';

class SampleData {
  static Future<void> addSamplePharmacies() async {
    final FirebaseFirestore firestore = FirebaseFirestore.instance;
    
    // Comprehensive list of Egyptian pharmacies with real locations
    final List<Map<String, dynamic>> pharmacies = [
      // Cairo - Downtown Area
      {
        'name': 'El-Salam Pharmacy',
        'nameAr': 'صيدلية السلام',
        'address': '15 Talaat Harb Street, Downtown Cairo',
        'addressAr': '١٥ شارع طلعت حرب، وسط البلد، القاهرة',
        'latitude': 30.0444,
        'longitude': 31.2357,
        'phone': '+20 2 2574 1234',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
          'Amoxicillin',
          'Azithromycin',
          'Ciprofloxacin',
        ],
      },
      {
        'name': 'Al-Nour Pharmacy',
        'nameAr': 'صيدلية النور',
        'address': '28 Kasr El-Nil Street, Downtown Cairo',
        'addressAr': '٢٨ شارع قصر النيل، وسط البلد، القاهرة',
        'latitude': 30.0588,
        'longitude': 31.2238,
        'phone': '+20 2 2574 5678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Folic Acid',
          'Zinc',
          'Magnesium',
        ],
      },
      {
        'name': 'Modern Pharmacy',
        'nameAr': 'الصيدلية الحديثة',
        'address': '45 Abdel Khalek Sarwat Street, Downtown Cairo',
        'addressAr': '٤٥ شارع عبد الخالق ثروت، وسط البلد، القاهرة',
        'latitude': 30.1136,
        'longitude': 31.3344,
        'phone': '+20 2 2574 9012',
        'workingHours': '9:00 AM - 10:00 PM',
        'isOpen': false,
        'availableMedicines': [
          'Amoxicillin',
          'Azithromycin',
          'Ciprofloxacin',
          'Metronidazole',
          'Doxycycline',
          'Clarithromycin',
          'Erythromycin',
        ],
      },
      
      // Cairo - Zamalek
      {
        'name': 'Zamalek Pharmacy',
        'nameAr': 'صيدلية الزمالك',
        'address': '12 Hassan Sabry Street, Zamalek, Cairo',
        'addressAr': '١٢ شارع حسن صبري، الزمالك، القاهرة',
        'latitude': 30.0588,
        'longitude': 31.2238,
        'phone': '+20 2 2735 1234',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Omeprazole',
          'Lansoprazole',
          'Pantoprazole',
          'Ranitidine',
          'Famotidine',
        ],
      },
      
      // Cairo - Heliopolis
      {
        'name': 'Heliopolis Pharmacy',
        'nameAr': 'صيدلية مصر الجديدة',
        'address': '78 Ibrahim El-Lakkani Street, Heliopolis, Cairo',
        'addressAr': '٧٨ شارع إبراهيم اللقاني، مصر الجديدة، القاهرة',
        'latitude': 30.1136,
        'longitude': 31.3344,
        'phone': '+20 2 2418 5678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Metformin',
          'Gliclazide',
          'Insulin',
          'Glimepiride',
          'Sitagliptin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Cairo - Maadi
      {
        'name': 'Maadi Pharmacy',
        'nameAr': 'صيدلية المعادي',
        'address': '34 Road 9, Maadi, Cairo',
        'addressAr': '٣٤ شارع ٩، المعادي، القاهرة',
        'latitude': 29.9792,
        'longitude': 31.1342,
        'phone': '+20 2 2524 9012',
        'workingHours': '7:00 AM - 12:00 AM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
          'Omega-3',
        ],
      },
      
      // Giza - Dokki
      {
        'name': 'Dokki Pharmacy',
        'nameAr': 'صيدلية الدقي',
        'address': '56 Tahrir Street, Dokki, Giza',
        'addressAr': '٥٦ شارع التحرير، الدقي، الجيزة',
        'latitude': 30.0330,
        'longitude': 31.2087,
        'phone': '+20 2 3748 1234',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Metformin',
          'Gliclazide',
          'Insulin',
          'Glimepiride',
          'Sitagliptin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
        ],
      },
      
      // Giza - Mohandessin
      {
        'name': 'Mohandessin Pharmacy',
        'nameAr': 'صيدلية المهندسين',
        'address': '89 Gameat El-Dowal Street, Mohandessin, Giza',
        'addressAr': '٨٩ شارع جامعة الدول، المهندسين، الجيزة',
        'latitude': 30.0444,
        'longitude': 31.1995,
        'phone': '+20 2 3748 5678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
          'B-Complex',
          'Folic Acid',
        ],
      },
      
      // Alexandria
      {
        'name': 'Alexandria Central Pharmacy',
        'nameAr': 'الصيدلية المركزية بالإسكندرية',
        'address': '23 Saad Zaghloul Street, Alexandria',
        'addressAr': '٢٣ شارع سعد زغلول، الإسكندرية',
        'latitude': 31.2001,
        'longitude': 29.9187,
        'phone': '+20 3 4872 1234',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
        ],
      },
      
      // Alexandria - Sidi Gaber
      {
        'name': 'Sidi Gaber Pharmacy',
        'nameAr': 'صيدلية سيدي جابر',
        'address': '45 El-Horreya Street, Sidi Gaber, Alexandria',
        'addressAr': '٤٥ شارع الحرية، سيدي جابر، الإسكندرية',
        'latitude': 31.2156,
        'longitude': 29.9557,
        'phone': '+20 3 4872 5678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Sharm El-Sheikh
      {
        'name': 'Sharm El-Sheikh Pharmacy',
        'nameAr': 'صيدلية شرم الشيخ',
        'address': '12 Peace Road, Sharm El-Sheikh',
        'addressAr': '١٢ طريق السلام، شرم الشيخ',
        'latitude': 27.9158,
        'longitude': 34.3300,
        'phone': '+20 69 3661 234',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Hurghada
      {
        'name': 'Hurghada Pharmacy',
        'nameAr': 'صيدلية الغردقة',
        'address': '78 Sheraton Road, Hurghada',
        'addressAr': '٧٨ طريق شيراتون، الغردقة',
        'latitude': 27.2579,
        'longitude': 33.8116,
        'phone': '+20 65 3546 789',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Luxor
      {
        'name': 'Luxor Pharmacy',
        'nameAr': 'صيدلية الأقصر',
        'address': '34 El-Karnak Street, Luxor',
        'addressAr': '٣٤ شارع الكرنك، الأقصر',
        'latitude': 25.6872,
        'longitude': 32.6396,
        'phone': '+20 97 2361 234',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Aswan
      {
        'name': 'Aswan Pharmacy',
        'nameAr': 'صيدلية أسوان',
        'address': '56 El-Nil Street, Aswan',
        'addressAr': '٥٦ شارع النيل، أسوان',
        'latitude': 24.0889,
        'longitude': 32.8998,
        'phone': '+20 97 2312 345',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Port Said
      {
        'name': 'Port Said Pharmacy',
        'nameAr': 'صيدلية بورسعيد',
        'address': '23 El-Shohada Street, Port Said',
        'addressAr': '٢٣ شارع الشهداء، بورسعيد',
        'latitude': 31.2667,
        'longitude': 32.3000,
        'phone': '+20 66 3221 456',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
        ],
      },
      
      // Suez
      {
        'name': 'Suez Pharmacy',
        'nameAr': 'صيدلية السويس',
        'address': '45 El-Gomhoreya Street, Suez',
        'addressAr': '٤٥ شارع الجمهورية، السويس',
        'latitude': 29.9668,
        'longitude': 32.5498,
        'phone': '+20 62 3198 765',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Ismailia
      {
        'name': 'Ismailia Pharmacy',
        'nameAr': 'صيدلية الإسماعيلية',
        'address': '67 El-Thawra Street, Ismailia',
        'addressAr': '٦٧ شارع الثورة، الإسماعيلية',
        'latitude': 30.6043,
        'longitude': 32.2723,
        'phone': '+20 64 3912 345',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Mansoura
      {
        'name': 'Mansoura Pharmacy',
        'nameAr': 'صيدلية المنصورة',
        'address': '89 El-Gomhoreya Street, Mansoura',
        'addressAr': '٨٩ شارع الجمهورية، المنصورة',
        'latitude': 31.0422,
        'longitude': 31.3800,
        'phone': '+20 50 2345 678',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
        ],
      },
      
      // Tanta
      {
        'name': 'Tanta Pharmacy',
        'nameAr': 'صيدلية طنطا',
        'address': '34 El-Sheikh Street, Tanta',
        'addressAr': '٣٤ شارع الشيخ، طنطا',
        'latitude': 30.7865,
        'longitude': 31.0004,
        'phone': '+20 40 3334 567',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Zagazig
      {
        'name': 'Zagazig Pharmacy',
        'nameAr': 'صيدلية الزقازيق',
        'address': '56 El-Shaheed Street, Zagazig',
        'addressAr': '٥٦ شارع الشهيد، الزقازيق',
        'latitude': 30.5877,
        'longitude': 31.5020,
        'phone': '+20 55 2345 678',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Beni Suef
      {
        'name': 'Beni Suef Pharmacy',
        'nameAr': 'صيدلية بني سويف',
        'address': '78 El-Nil Street, Beni Suef',
        'addressAr': '٧٨ شارع النيل، بني سويف',
        'latitude': 29.0744,
        'longitude': 31.0972,
        'phone': '+20 82 2345 678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Minya
      {
        'name': 'Minya Pharmacy',
        'nameAr': 'صيدلية المنيا',
        'address': '23 El-Corniche Street, Minya',
        'addressAr': '٢٣ شارع الكورنيش، المنيا',
        'latitude': 28.1094,
        'longitude': 30.7503,
        'phone': '+20 86 2345 678',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
      
      // Assiut
      {
        'name': 'Assiut Pharmacy',
        'nameAr': 'صيدلية أسيوط',
        'address': '45 El-Thawra Street, Assiut',
        'addressAr': '٤٥ شارع الثورة، أسيوط',
        'latitude': 27.1828,
        'longitude': 31.1828,
        'phone': '+20 88 2345 678',
        'workingHours': '24/7',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
          'Simvastatin',
          'Atorvastatin',
        ],
      },
      
      // Sohag
      {
        'name': 'Sohag Pharmacy',
        'nameAr': 'صيدلية سوهاج',
        'address': '67 El-Gomhoreya Street, Sohag',
        'addressAr': '٦٧ شارع الجمهورية، سوهاج',
        'latitude': 26.5569,
        'longitude': 31.6947,
        'phone': '+20 93 2345 678',
        'workingHours': '8:00 AM - 11:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Vitamin C',
          'Vitamin D',
          'Calcium',
          'Iron Supplements',
          'Zinc',
          'Magnesium',
        ],
      },
      
      // Qena
      {
        'name': 'Qena Pharmacy',
        'nameAr': 'صيدلية قنا',
        'address': '89 El-Nil Street, Qena',
        'addressAr': '٨٩ شارع النيل، قنا',
        'latitude': 26.1644,
        'longitude': 32.7267,
        'phone': '+20 96 2345 678',
        'workingHours': '8:00 AM - 10:00 PM',
        'isOpen': true,
        'availableMedicines': [
          'Panadol',
          'Paracetamol',
          'Ibuprofen',
          'Aspirin',
          'Amoxicillin',
          'Azithromycin',
          'Omeprazole',
          'Metformin',
          'Amlodipine',
          'Losartan',
          'Atenolol',
        ],
      },
    ];

    try {
      // Add each pharmacy to Firestore
      for (var pharmacy in pharmacies) {
        await firestore.collection('pharmacies').add(pharmacy);
        print('Added pharmacy: ${pharmacy['name']}');
      }
      print('✅ All sample pharmacies added successfully!');
    } catch (e) {
      print('❌ Error adding sample pharmacies: $e');
    }
  }

  static Future<void> addSampleMedicines() async {
    final FirebaseFirestore firestore = FirebaseFirestore.instance;
    
    // Comprehensive list of common medicines in Egypt
    final List<Map<String, dynamic>> medicines = [
      {
        'nameEn': 'Panadol',
        'nameAr': 'بنادول',
        'descriptionEn': 'Pain reliever and fever reducer containing paracetamol. Used to treat mild to moderate pain and fever.',
        'descriptionAr': 'مسكن للألم وخافض للحرارة يحتوي على باراسيتامول. يستخدم لعلاج الألم الخفيف إلى المتوسط والحمى.',
        'category': 'Pain Relief',
        'categoryAr': 'مسكنات الألم',
        'dosage': '500-1000mg every 4-6 hours',
        'dosageAr': '٥٠٠-١٠٠٠ ملجم كل ٤-٦ ساعات',
        'sideEffects': 'Nausea, stomach upset, allergic reactions',
        'sideEffectsAr': 'غثيان، اضطراب في المعدة، ردود فعل تحسسية',
        'price': '15-25 EGP',
        'priceAr': '١٥-٢٥ جنيه',
      },
      {
        'nameEn': 'Paracetamol',
        'nameAr': 'باراسيتامول',
        'descriptionEn': 'Generic pain reliever and fever reducer. Used to treat mild to moderate pain and fever.',
        'descriptionAr': 'مسكن للألم وخافض للحرارة عام. يستخدم لعلاج الألم الخفيف إلى المتوسط والحمى.',
        'category': 'Pain Relief',
        'categoryAr': 'مسكنات الألم',
        'dosage': '500-1000mg every 4-6 hours',
        'dosageAr': '٥٠٠-١٠٠٠ ملجم كل ٤-٦ ساعات',
        'sideEffects': 'Nausea, stomach upset, allergic reactions',
        'sideEffectsAr': 'غثيان، اضطراب في المعدة، ردود فعل تحسسية',
        'price': '8-15 EGP',
        'priceAr': '٨-١٥ جنيه',
      },
      {
        'nameEn': 'Ibuprofen',
        'nameAr': 'ايبوبروفين',
        'descriptionEn': 'Nonsteroidal anti-inflammatory drug used to reduce pain, fever, and inflammation.',
        'descriptionAr': 'دواء مضاد للالتهابات غير ستيرويدي يستخدم لتقليل الألم والحمى والالتهاب.',
        'category': 'Anti-inflammatory',
        'categoryAr': 'مضاد للالتهابات',
        'dosage': '200-400mg every 4-6 hours',
        'dosageAr': '٢٠٠-٤٠٠ ملجم كل ٤-٦ ساعات',
        'sideEffects': 'Stomach irritation, ulcers, kidney problems',
        'sideEffectsAr': 'تهيج المعدة، قرح، مشاكل في الكلى',
        'price': '12-20 EGP',
        'priceAr': '١٢-٢٠ جنيه',
      },
      {
        'nameEn': 'Aspirin',
        'nameAr': 'أسبرين',
        'descriptionEn': 'Used to reduce pain, fever, or inflammation. Also used as a blood thinner.',
        'descriptionAr': 'يستخدم لتقليل الألم أو الحمى أو الالتهاب. يستخدم أيضاً كمضاد للتجلط.',
        'category': 'Pain Relief',
        'categoryAr': 'مسكنات الألم',
        'dosage': '325-650mg every 4-6 hours',
        'dosageAr': '٣٢٥-٦٥٠ ملجم كل ٤-٦ ساعات',
        'sideEffects': 'Stomach bleeding, ulcers, ringing in ears',
        'sideEffectsAr': 'نزيف المعدة، قرح، طنين في الأذنين',
        'price': '5-12 EGP',
        'priceAr': '٥-١٢ جنيه',
      },
      {
        'nameEn': 'Amoxicillin',
        'nameAr': 'أموكسيسيلين',
        'descriptionEn': 'Antibiotic used to treat bacterial infections such as pneumonia, bronchitis, and ear infections.',
        'descriptionAr': 'مضاد حيوي يستخدم لعلاج الالتهابات البكتيرية مثل الالتهاب الرئوي والتهاب الشعب الهوائية والتهابات الأذن.',
        'category': 'Antibiotic',
        'categoryAr': 'مضاد حيوي',
        'dosage': '250-500mg three times daily',
        'dosageAr': '٢٥٠-٥٠٠ ملجم ثلاث مرات يومياً',
        'sideEffects': 'Diarrhea, nausea, allergic reactions',
        'sideEffectsAr': 'إسهال، غثيان، ردود فعل تحسسية',
        'price': '25-40 EGP',
        'priceAr': '٢٥-٤٠ جنيه',
      },
      {
        'nameEn': 'Azithromycin',
        'nameAr': 'أزيثروميسين',
        'descriptionEn': 'Antibiotic used to treat various bacterial infections including respiratory infections.',
        'descriptionAr': 'مضاد حيوي يستخدم لعلاج الالتهابات البكتيرية المختلفة بما في ذلك التهابات الجهاز التنفسي.',
        'category': 'Antibiotic',
        'categoryAr': 'مضاد حيوي',
        'dosage': '500mg once daily for 3 days',
        'dosageAr': '٥٠٠ ملجم مرة واحدة يومياً لمدة ٣ أيام',
        'sideEffects': 'Nausea, diarrhea, stomach pain',
        'sideEffectsAr': 'غثيان، إسهال، ألم في المعدة',
        'price': '35-55 EGP',
        'priceAr': '٣٥-٥٥ جنيه',
      },
      {
        'nameEn': 'Omeprazole',
        'nameAr': 'أوميبرازول',
        'descriptionEn': 'Proton pump inhibitor used to treat acid reflux, ulcers, and heartburn.',
        'descriptionAr': 'مثبط مضخة البروتون يستخدم لعلاج ارتجاع الحمض والقرح وحرقة المعدة.',
        'category': 'Gastric Acid Suppressant',
        'categoryAr': 'مثبط حمض المعدة',
        'dosage': '20-40mg once daily',
        'dosageAr': '٢٠-٤٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Headache, diarrhea, abdominal pain',
        'sideEffectsAr': 'صداع، إسهال، ألم في البطن',
        'price': '30-50 EGP',
        'priceAr': '٣٠-٥٠ جنيه',
      },
      {
        'nameEn': 'Metformin',
        'nameAr': 'ميتفورمين',
        'descriptionEn': 'Oral diabetes medicine that helps control blood sugar levels.',
        'descriptionAr': 'دواء السكري الفموي الذي يساعد في التحكم في مستويات السكر في الدم.',
        'category': 'Antidiabetic',
        'categoryAr': 'مضاد للسكري',
        'dosage': '500-2000mg daily in divided doses',
        'dosageAr': '٥٠٠-٢٠٠٠ ملجم يومياً مقسمة على جرعات',
        'sideEffects': 'Nausea, diarrhea, lactic acidosis',
        'sideEffectsAr': 'غثيان، إسهال، حمض اللاكتيك',
        'price': '20-35 EGP',
        'priceAr': '٢٠-٣٥ جنيه',
      },
      {
        'nameEn': 'Amlodipine',
        'nameAr': 'أملوديبين',
        'descriptionEn': 'Calcium channel blocker used to treat high blood pressure and chest pain.',
        'descriptionAr': 'حاصر قنوات الكالسيوم يستخدم لعلاج ارتفاع ضغط الدم وألم الصدر.',
        'category': 'Antihypertensive',
        'categoryAr': 'مضاد لارتفاع ضغط الدم',
        'dosage': '2.5-10mg once daily',
        'dosageAr': '٢.٥-١٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Swelling, dizziness, flushing',
        'sideEffectsAr': 'تورم، دوخة، احمرار',
        'price': '25-40 EGP',
        'priceAr': '٢٥-٤٠ جنيه',
      },
      {
        'nameEn': 'Losartan',
        'nameAr': 'لوسارتان',
        'descriptionEn': 'Angiotensin receptor blocker used to treat high blood pressure.',
        'descriptionAr': 'حاصر مستقبلات الأنجيوتنسين يستخدم لعلاج ارتفاع ضغط الدم.',
        'category': 'Antihypertensive',
        'categoryAr': 'مضاد لارتفاع ضغط الدم',
        'dosage': '25-100mg once daily',
        'dosageAr': '٢٥-١٠٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Dizziness, fatigue, cough',
        'sideEffectsAr': 'دوخة، إرهاق، سعال',
        'price': '30-45 EGP',
        'priceAr': '٣٠-٤٥ جنيه',
      },
      {
        'nameEn': 'Atenolol',
        'nameAr': 'أتينولول',
        'descriptionEn': 'Beta blocker used to treat high blood pressure and heart conditions.',
        'descriptionAr': 'حاصر بيتا يستخدم لعلاج ارتفاع ضغط الدم وأمراض القلب.',
        'category': 'Beta Blocker',
        'categoryAr': 'حاصر بيتا',
        'dosage': '25-100mg once daily',
        'dosageAr': '٢٥-١٠٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Fatigue, cold hands, dizziness',
        'sideEffectsAr': 'إرهاق، برودة في اليدين، دوخة',
        'price': '15-30 EGP',
        'priceAr': '١٥-٣٠ جنيه',
      },
      {
        'nameEn': 'Simvastatin',
        'nameAr': 'سيمفاستاتين',
        'descriptionEn': 'Statin medication used to lower cholesterol levels.',
        'descriptionAr': 'دواء ستاتين يستخدم لخفض مستويات الكوليسترول.',
        'category': 'Statin',
        'categoryAr': 'ستاتين',
        'dosage': '10-80mg once daily',
        'dosageAr': '١٠-٨٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Muscle pain, liver problems, digestive issues',
        'sideEffectsAr': 'ألم في العضلات، مشاكل في الكبد، مشاكل هضمية',
        'price': '40-60 EGP',
        'priceAr': '٤٠-٦٠ جنيه',
      },
      {
        'nameEn': 'Atorvastatin',
        'nameAr': 'أتورفاستاتين',
        'descriptionEn': 'Statin medication used to lower cholesterol and prevent heart disease.',
        'descriptionAr': 'دواء ستاتين يستخدم لخفض الكوليسترول والوقاية من أمراض القلب.',
        'category': 'Statin',
        'categoryAr': 'ستاتين',
        'dosage': '10-80mg once daily',
        'dosageAr': '١٠-٨٠ ملجم مرة واحدة يومياً',
        'sideEffects': 'Muscle pain, liver problems, digestive issues',
        'sideEffectsAr': 'ألم في العضلات، مشاكل في الكبد، مشاكل هضمية',
        'price': '45-70 EGP',
        'priceAr': '٤٥-٧٠ جنيه',
      },
      {
        'nameEn': 'Vitamin C',
        'nameAr': 'فيتامين سي',
        'descriptionEn': 'Essential vitamin for immune system support and antioxidant protection.',
        'descriptionAr': 'فيتامين أساسي لدعم الجهاز المناعي والحماية المضادة للأكسدة.',
        'category': 'Vitamin',
        'categoryAr': 'فيتامين',
        'dosage': '500-1000mg daily',
        'dosageAr': '٥٠٠-١٠٠٠ ملجم يومياً',
        'sideEffects': 'Diarrhea, nausea in high doses',
        'sideEffectsAr': 'إسهال، غثيان في الجرعات العالية',
        'price': '10-25 EGP',
        'priceAr': '١٠-٢٥ جنيه',
      },
      {
        'nameEn': 'Vitamin D',
        'nameAr': 'فيتامين د',
        'descriptionEn': 'Essential vitamin for bone health and immune system function.',
        'descriptionAr': 'فيتامين أساسي لصحة العظام ووظيفة الجهاز المناعي.',
        'category': 'Vitamin',
        'categoryAr': 'فيتامين',
        'dosage': '400-2000 IU daily',
        'dosageAr': '٤٠٠-٢٠٠٠ وحدة دولية يومياً',
        'sideEffects': 'Nausea, weakness in high doses',
        'sideEffectsAr': 'غثيان، ضعف في الجرعات العالية',
        'price': '15-35 EGP',
        'priceAr': '١٥-٣٥ جنيه',
      },
      {
        'nameEn': 'Calcium',
        'nameAr': 'كالسيوم',
        'descriptionEn': 'Essential mineral for bone health and muscle function.',
        'descriptionAr': 'معدن أساسي لصحة العظام ووظيفة العضلات.',
        'category': 'Mineral',
        'categoryAr': 'معدن',
        'dosage': '500-1000mg daily',
        'dosageAr': '٥٠٠-١٠٠٠ ملجم يومياً',
        'sideEffects': 'Constipation, gas, bloating',
        'sideEffectsAr': 'إمساك، غازات، انتفاخ',
        'price': '20-40 EGP',
        'priceAr': '٢٠-٤٠ جنيه',
      },
      {
        'nameEn': 'Iron Supplements',
        'nameAr': 'مكملات الحديد',
        'descriptionEn': 'Used to treat iron deficiency anemia.',
        'descriptionAr': 'يستخدم لعلاج فقر الدم الناجم عن نقص الحديد.',
        'category': 'Mineral',
        'categoryAr': 'معدن',
        'dosage': '30-60mg daily',
        'dosageAr': '٣٠-٦٠ ملجم يومياً',
        'sideEffects': 'Constipation, black stools, stomach upset',
        'sideEffectsAr': 'إمساك، براز أسود، اضطراب في المعدة',
        'price': '25-45 EGP',
        'priceAr': '٢٥-٤٥ جنيه',
      },
      {
        'nameEn': 'Zinc',
        'nameAr': 'زنك',
        'descriptionEn': 'Essential mineral for immune system and wound healing.',
        'descriptionAr': 'معدن أساسي للجهاز المناعي والتئام الجروح.',
        'category': 'Mineral',
        'categoryAr': 'معدن',
        'dosage': '15-30mg daily',
        'dosageAr': '١٥-٣٠ ملجم يومياً',
        'sideEffects': 'Nausea, vomiting, diarrhea',
        'sideEffectsAr': 'غثيان، قيء، إسهال',
        'price': '15-30 EGP',
        'priceAr': '١٥-٣٠ جنيه',
      },
      {
        'nameEn': 'Magnesium',
        'nameAr': 'ماغنيسيوم',
        'descriptionEn': 'Essential mineral for muscle and nerve function.',
        'descriptionAr': 'معدن أساسي لوظيفة العضلات والأعصاب.',
        'category': 'Mineral',
        'categoryAr': 'معدن',
        'dosage': '200-400mg daily',
        'dosageAr': '٢٠٠-٤٠٠ ملجم يومياً',
        'sideEffects': 'Diarrhea, nausea, stomach cramps',
        'sideEffectsAr': 'إسهال، غثيان، تقلصات في المعدة',
        'price': '20-35 EGP',
        'priceAr': '٢٠-٣٥ جنيه',
      },
    ];

    try {
      // Add each medicine to Firestore
      for (var medicine in medicines) {
        await firestore.collection('medicines').add(medicine);
        print('Added medicine: ${medicine['nameEn']}');
      }
      print('✅ All sample medicines added successfully!');
    } catch (e) {
      print('❌ Error adding sample medicines: $e');
    }
  }

  // Function to populate both pharmacies and medicines
  static Future<void> populateSampleData() async {
    print('🚀 Starting to populate sample data...');
    await addSampleMedicines();
    await addSamplePharmacies();
    print('✅ Sample data population completed!');
  }
}